export const appActions = {
    LOGIN: 'LOGIN',
    GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
    GET_USER: 'GET_USER',
    RESET_ERROR: 'RESET_ERROR',
    SET_LOADING: 'SET_LOADING',
    GET_PROBLEM_LIST: 'GET_PROBLEM_LIST',
    SUBMIT_ANSWER: 'SUBMIT_ANSWER',
    GET_TOPIC_LIST: 'GET_TOPIC_LIST',
    DELETE_TOPIC: 'DELETE_TOPIC',
    UPDATE_TOPIC: 'UPDATE_TOPIC',
    CREATE_TOPIC: 'CREATE_TOPIC',
    GET_PROBLEM_DETAIL: 'GET_PROBLEM_DETAIL',
  };
  